### ISSUE TITLE
Python3 PIP

### ISSUE THREAD

**Issue by superudo** [timofurrer/ariseem#1]
If you use Python3 image, shouldn't the `pip` command be `pip3`?

**Comment by timofurrer** [comment]
That really depends on your installation.
If there is only Python 3 installed, like in the docker image, the pip command will be `pip`.
Distributions like Ubuntu and debian use `pip` for Python 2 and `pip3` for Python 3, so that the `python-pip` and `python3-pip` packages can be installed on the same system without a conflict.
